### ISSUE TITLE
所感

### ISSUE THREAD

**Issue by kenbun** [AkashiSN/Information-Engineering-Experiment#8]
所感2～3行で書いていきましょ

**Comment by John-bardera** [comment]
有線所感
今回の実験で最も難しい課題だと感じた。なぜなら今まで対戦することなく、学習してこなかった分野に触れることとなったからである。しかし、そのためとても興味深くまた、有意義な実験であったと思う。今回は、IPv6についての実験は行うことはできなかったが、また機会があれば学びたいと思う。

**Comment by John-bardera** [comment]
LANケーブル作成所感
nslookupコマンドを使い、実際にどのようにIPアドレスが振られているかを実際に確認した。IPアドレスが使われていることは授業などから知ってはいたが、実際にどう割り振られ、どういう処理をされているかを見るのは新鮮で有意義であった。

**Comment by kenbun** [comment]
4:Wirelessの所感
いつも当たり前のように使っているけどあまりよく知らないWifiを実験を通して設定や特性などよく知れてよかった。また、wifi以外でもこの実験を通して学べてよりネットワークに対する認識が深まったと思う。
SSIDの強度対距離の測定では2.4GHzと5GHzの違いがよくわかり非常に面白い実験だった。また、障害物があった時など条件を変えてやってみるとどうなるんだろうと好奇心が沸いた。
これからの時代ネットワークとは切り離せない世の中になっていく、なのでネットワークについてさらに深く知っていくことも特にこれから情報を学ぶものとして必要ではないかと考えることが出来た。

**Comment by Tasika** [comment]
IPアドレスの構造などネットワークの基礎について理解が深まったと思う。しかし、実験において一般に速度重視の通信方式であるUDPの帯域性能がTCPのものに劣った結果が出たことが不思議だ。
